services:
  postgres:
    image: postgres:16
    container_name: incidentops_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - incidentops_pgdata:/var/lib/postgresql/data
  
  api:
    build:
      context: .
      dockerfile: apps/api/dockerfile
    container_name: api-container
    env_file:
      - apps/api/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  

  worker:
    build:
      context: .
      dockerfile: apps/workers/dockerfile
    container_name: worker_container
    env_file:
      - apps/workers/.env
    depends_on:
      - postgres

volumes:
  incidentops_pgdata: